defaults: &defaults
  name: Encen

production:
  <<: *defaults
  exception_notification_sender: your_account@mail.com
  exception_notification_recipient: who_will_be_notified@me.com
  mail:
    account:
      user_name: some@address.com
      password: password
    smtp:
      address: smtp.example.com
      port: 555
      domain: domain.com
      authentication: plain
      enable_starttls_auto: true

  hostname: yourapp.com
  hosting: true

  hosts:
    bombi-abogados.es: es
    bombi-advocats.cat: ca


development:
  <<: *defaults
  mail:
    account:
      user_name: some@address.com
      password: password
    smtp:
      address: smtp.example.com
      port: 555
      domain: domain.com
      authentication: plain
      enable_starttls_auto: true

  hostname: localhost:3000
  hosting: false

  hosts:
    bombi-abogados.es: es
    bombi-advocats.cat: ca
