defaults: &defaults
  name: Encen
  seed: some_seed_token
  mailchimp_key: somekey-us2

production:
  <<: *defaults
  exception_notification_sender: your_account@mail.com
  exception_notification_recipient: who_will_be_notified@me.com
  storage:
    s3_access: some_access_key
    s3_secret: some_secret_key
  mail:
    account:
      user_name: some@address.com
      password: password
    smtp:
      address: smtp.example.com
      port: 555
      domain: domain.com
      authentication: plain
      enable_starttls_auto: true

  hostname: yourapp.com


development:
  <<: *defaults
  storage:
    s3_access: some_access_key
    s3_secret: some_secret_key
  mail:
    account:
      user_name: some@address.com
      password: password
    smtp:
      address: smtp.example.com
      port: 555
      domain: domain.com
      authentication: plain
      enable_starttls_auto: true

  hostname: localhost:3000
